//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundHandlingWeb.ARSReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseException", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException))]
    public partial class BaseException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ARSException", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
    [System.SerializableAttribute()]
    public partial class ARSException : RefundHandlingWeb.ARSReference.BaseException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/ARSLayer")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialAntwortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TransIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitialAntwort {
            get {
                return this.InitialAntwortField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialAntwortField, value) != true)) {
                    this.InitialAntwortField = value;
                    this.RaisePropertyChanged("InitialAntwort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransId {
            get {
                return this.TransIdField;
            }
            set {
                if ((this.TransIdField.Equals(value) != true)) {
                    this.TransIdField = value;
                    this.RaisePropertyChanged("TransId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComponentMessage", Namespace="http://schemas.datacontract.org/2004/07/ARSLayer")]
    [System.SerializableAttribute()]
    public partial class ComponentMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stepField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query {
            get {
                return this.QueryField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryField, value) != true)) {
                    this.QueryField = value;
                    this.RaisePropertyChanged("Query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int step {
            get {
                return this.stepField;
            }
            set {
                if ((this.stepField.Equals(value) != true)) {
                    this.stepField = value;
                    this.RaisePropertyChanged("step");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FareDisplay", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
    [System.SerializableAttribute()]
    public partial class FareDisplay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RefundHandlingWeb.ARSReference.FareDisplay.Fare[] FaresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Airline {
            get {
                return this.AirlineField;
            }
            set {
                if ((object.ReferenceEquals(this.AirlineField, value) != true)) {
                    this.AirlineField = value;
                    this.RaisePropertyChanged("Airline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RefundHandlingWeb.ARSReference.FareDisplay.Fare[] Fares {
            get {
                return this.FaresField;
            }
            set {
                if ((object.ReferenceEquals(this.FaresField, value) != true)) {
                    this.FaresField = value;
                    this.RaisePropertyChanged("Fares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terminal {
            get {
                return this.TerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalField, value) != true)) {
                    this.TerminalField = value;
                    this.RaisePropertyChanged("Terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="FareDisplay.Fare", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
        [System.SerializableAttribute()]
        public partial class Fare : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string COResponseField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string EoEField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FTCField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FareBasisField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string LineField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string OWField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RTField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RestrictionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RuleField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string SRResponseField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string includesHRField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string COResponse {
                get {
                    return this.COResponseField;
                }
                set {
                    if ((object.ReferenceEquals(this.COResponseField, value) != true)) {
                        this.COResponseField = value;
                        this.RaisePropertyChanged("COResponse");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string EoE {
                get {
                    return this.EoEField;
                }
                set {
                    if ((object.ReferenceEquals(this.EoEField, value) != true)) {
                        this.EoEField = value;
                        this.RaisePropertyChanged("EoE");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FTC {
                get {
                    return this.FTCField;
                }
                set {
                    if ((object.ReferenceEquals(this.FTCField, value) != true)) {
                        this.FTCField = value;
                        this.RaisePropertyChanged("FTC");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FareBasis {
                get {
                    return this.FareBasisField;
                }
                set {
                    if ((object.ReferenceEquals(this.FareBasisField, value) != true)) {
                        this.FareBasisField = value;
                        this.RaisePropertyChanged("FareBasis");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Line {
                get {
                    return this.LineField;
                }
                set {
                    if ((object.ReferenceEquals(this.LineField, value) != true)) {
                        this.LineField = value;
                        this.RaisePropertyChanged("Line");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string OW {
                get {
                    return this.OWField;
                }
                set {
                    if ((object.ReferenceEquals(this.OWField, value) != true)) {
                        this.OWField = value;
                        this.RaisePropertyChanged("OW");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RT {
                get {
                    return this.RTField;
                }
                set {
                    if ((object.ReferenceEquals(this.RTField, value) != true)) {
                        this.RTField = value;
                        this.RaisePropertyChanged("RT");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Restriction {
                get {
                    return this.RestrictionField;
                }
                set {
                    if ((object.ReferenceEquals(this.RestrictionField, value) != true)) {
                        this.RestrictionField = value;
                        this.RaisePropertyChanged("Restriction");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Rule {
                get {
                    return this.RuleField;
                }
                set {
                    if ((object.ReferenceEquals(this.RuleField, value) != true)) {
                        this.RuleField = value;
                        this.RaisePropertyChanged("Rule");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string SRResponse {
                get {
                    return this.SRResponseField;
                }
                set {
                    if ((object.ReferenceEquals(this.SRResponseField, value) != true)) {
                        this.SRResponseField = value;
                        this.RaisePropertyChanged("SRResponse");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string includesHR {
                get {
                    return this.includesHRField;
                }
                set {
                    if ((object.ReferenceEquals(this.includesHRField, value) != true)) {
                        this.includesHRField = value;
                        this.RaisePropertyChanged("includesHR");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelayedAnswerException", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
    [System.SerializableAttribute()]
    public partial class DelayedAnswerException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstimatedWaittimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodtoRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OperationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstimatedWaittime {
            get {
                return this.EstimatedWaittimeField;
            }
            set {
                if ((this.EstimatedWaittimeField.Equals(value) != true)) {
                    this.EstimatedWaittimeField = value;
                    this.RaisePropertyChanged("EstimatedWaittime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodtoRequest {
            get {
                return this.MethodtoRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodtoRequestField, value) != true)) {
                    this.MethodtoRequestField = value;
                    this.RaisePropertyChanged("MethodtoRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((this.OperationIdField.Equals(value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HRS_RetrieveEmailFromPNRResponse", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
    [System.SerializableAttribute()]
    public partial class HRS_RetrieveEmailFromPNRResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ListofEmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListofEmails {
            get {
                return this.ListofEmailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListofEmailsField, value) != true)) {
                    this.ListofEmailsField = value;
                    this.RaisePropertyChanged("ListofEmails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundAppInfo", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
    [System.SerializableAttribute()]
    public partial class RefundAppInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RefundHandlingWeb.ARSReference.RefundInfo riField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RefundHandlingWeb.ARSReference.RefundInfo ri {
            get {
                return this.riField;
            }
            set {
                if ((object.ReferenceEquals(this.riField, value) != true)) {
                    this.riField = value;
                    this.RaisePropertyChanged("ri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundInfo", Namespace="http://schemas.datacontract.org/2004/07/SharedModel")]
    [System.SerializableAttribute()]
    public partial class RefundInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIATACodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirlineCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket1IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket2IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket3IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket4IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConjunctionTicket5IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FareBasisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlatFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormofPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassengerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvidedEMailAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefundApplicationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefundApplicationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefundTicketCouponNumberIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefundedFareAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefundedTicketNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxAmountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaiverCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentComment {
            get {
                return this.AgentCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentCommentField, value) != true)) {
                    this.AgentCommentField = value;
                    this.RaisePropertyChanged("AgentComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentIATACode {
            get {
                return this.AgentIATACodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIATACodeField, value) != true)) {
                    this.AgentIATACodeField = value;
                    this.RaisePropertyChanged("AgentIATACode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirlineCode {
            get {
                return this.AirlineCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AirlineCodeField, value) != true)) {
                    this.AirlineCodeField = value;
                    this.RaisePropertyChanged("AirlineCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commission {
            get {
                return this.CommissionField;
            }
            set {
                if ((object.ReferenceEquals(this.CommissionField, value) != true)) {
                    this.CommissionField = value;
                    this.RaisePropertyChanged("Commission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket1 {
            get {
                return this.ConjunctionTicket1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket1Field, value) != true)) {
                    this.ConjunctionTicket1Field = value;
                    this.RaisePropertyChanged("ConjunctionTicket1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket1Identifier {
            get {
                return this.ConjunctionTicket1IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket1IdentifierField, value) != true)) {
                    this.ConjunctionTicket1IdentifierField = value;
                    this.RaisePropertyChanged("ConjunctionTicket1Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket2 {
            get {
                return this.ConjunctionTicket2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket2Field, value) != true)) {
                    this.ConjunctionTicket2Field = value;
                    this.RaisePropertyChanged("ConjunctionTicket2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket2Identifier {
            get {
                return this.ConjunctionTicket2IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket2IdentifierField, value) != true)) {
                    this.ConjunctionTicket2IdentifierField = value;
                    this.RaisePropertyChanged("ConjunctionTicket2Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket3 {
            get {
                return this.ConjunctionTicket3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket3Field, value) != true)) {
                    this.ConjunctionTicket3Field = value;
                    this.RaisePropertyChanged("ConjunctionTicket3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket3Identifier {
            get {
                return this.ConjunctionTicket3IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket3IdentifierField, value) != true)) {
                    this.ConjunctionTicket3IdentifierField = value;
                    this.RaisePropertyChanged("ConjunctionTicket3Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket4 {
            get {
                return this.ConjunctionTicket4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket4Field, value) != true)) {
                    this.ConjunctionTicket4Field = value;
                    this.RaisePropertyChanged("ConjunctionTicket4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket4Identifier {
            get {
                return this.ConjunctionTicket4IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket4IdentifierField, value) != true)) {
                    this.ConjunctionTicket4IdentifierField = value;
                    this.RaisePropertyChanged("ConjunctionTicket4Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket5 {
            get {
                return this.ConjunctionTicket5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket5Field, value) != true)) {
                    this.ConjunctionTicket5Field = value;
                    this.RaisePropertyChanged("ConjunctionTicket5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConjunctionTicket5Identifier {
            get {
                return this.ConjunctionTicket5IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ConjunctionTicket5IdentifierField, value) != true)) {
                    this.ConjunctionTicket5IdentifierField = value;
                    this.RaisePropertyChanged("ConjunctionTicket5Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FareBasis {
            get {
                return this.FareBasisField;
            }
            set {
                if ((object.ReferenceEquals(this.FareBasisField, value) != true)) {
                    this.FareBasisField = value;
                    this.RaisePropertyChanged("FareBasis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlatFileName {
            get {
                return this.FlatFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FlatFileNameField, value) != true)) {
                    this.FlatFileNameField = value;
                    this.RaisePropertyChanged("FlatFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormofPayment {
            get {
                return this.FormofPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.FormofPaymentField, value) != true)) {
                    this.FormofPaymentField = value;
                    this.RaisePropertyChanged("FormofPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassengerName {
            get {
                return this.PassengerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PassengerNameField, value) != true)) {
                    this.PassengerNameField = value;
                    this.RaisePropertyChanged("PassengerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvidedEMailAddresses {
            get {
                return this.ProvidedEMailAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvidedEMailAddressesField, value) != true)) {
                    this.ProvidedEMailAddressesField = value;
                    this.RaisePropertyChanged("ProvidedEMailAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundApplicationDate {
            get {
                return this.RefundApplicationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundApplicationDateField, value) != true)) {
                    this.RefundApplicationDateField = value;
                    this.RaisePropertyChanged("RefundApplicationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundApplicationNumber {
            get {
                return this.RefundApplicationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundApplicationNumberField, value) != true)) {
                    this.RefundApplicationNumberField = value;
                    this.RaisePropertyChanged("RefundApplicationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundTicketCouponNumberIdentifier {
            get {
                return this.RefundTicketCouponNumberIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundTicketCouponNumberIdentifierField, value) != true)) {
                    this.RefundTicketCouponNumberIdentifierField = value;
                    this.RaisePropertyChanged("RefundTicketCouponNumberIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundedFareAmount {
            get {
                return this.RefundedFareAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundedFareAmountField, value) != true)) {
                    this.RefundedFareAmountField = value;
                    this.RaisePropertyChanged("RefundedFareAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefundedTicketNumber {
            get {
                return this.RefundedTicketNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RefundedTicketNumberField, value) != true)) {
                    this.RefundedTicketNumberField = value;
                    this.RaisePropertyChanged("RefundedTicketNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxAmounts {
            get {
                return this.TaxAmountsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxAmountsField, value) != true)) {
                    this.TaxAmountsField = value;
                    this.RaisePropertyChanged("TaxAmounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaiverCode {
            get {
                return this.WaiverCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WaiverCodeField, value) != true)) {
                    this.WaiverCodeField = value;
                    this.RaisePropertyChanged("WaiverCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ARSReference.IARS")]
    public interface IARS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_SendSingleCommand", ReplyAction="http://tempuri.org/IARS/Kern_SendSingleCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_SSC00")]
        string Kern_SendSingleCommand(System.Guid AuthToken, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_SendSingleCommand", ReplyAction="http://tempuri.org/IARS/Kern_SendSingleCommandResponse")]
        System.Threading.Tasks.Task<string> Kern_SendSingleCommandAsync(System.Guid AuthToken, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_StartMultipleCommand", ReplyAction="http://tempuri.org/IARS/Kern_StartMultipleCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_StMC00")]
        RefundHandlingWeb.ARSReference.Transaction Kern_StartMultipleCommand(System.Guid AuthToken, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_StartMultipleCommand", ReplyAction="http://tempuri.org/IARS/Kern_StartMultipleCommandResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.Transaction> Kern_StartMultipleCommandAsync(System.Guid AuthToken, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_SendMultipleCommand", ReplyAction="http://tempuri.org/IARS/Kern_SendMultipleCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_SeMC00")]
        string Kern_SendMultipleCommand(System.Guid AuthToken, System.Guid TransactionId, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_SendMultipleCommand", ReplyAction="http://tempuri.org/IARS/Kern_SendMultipleCommandResponse")]
        System.Threading.Tasks.Task<string> Kern_SendMultipleCommandAsync(System.Guid AuthToken, System.Guid TransactionId, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_SendMultipleCommandNoWait", ReplyAction="http://tempuri.org/IARS/Kern_SendMultipleCommandNoWaitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_SeMCNW00")]
        string Kern_SendMultipleCommandNoWait(System.Guid AuthToken, System.Guid TransactionId, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_SendMultipleCommandNoWait", ReplyAction="http://tempuri.org/IARS/Kern_SendMultipleCommandNoWaitResponse")]
        System.Threading.Tasks.Task<string> Kern_SendMultipleCommandNoWaitAsync(System.Guid AuthToken, System.Guid TransactionId, string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_EndMultipleCommand", ReplyAction="http://tempuri.org/IARS/Kern_EndMultipleCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_EMC00")]
        void Kern_EndMultipleCommand(System.Guid AuthToken, System.Guid TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_EndMultipleCommand", ReplyAction="http://tempuri.org/IARS/Kern_EndMultipleCommandResponse")]
        System.Threading.Tasks.Task Kern_EndMultipleCommandAsync(System.Guid AuthToken, System.Guid TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_GetProgress", ReplyAction="http://tempuri.org/IARS/Kern_GetProgressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_GP00")]
        string Kern_GetProgress(System.Guid AuthToken, System.Guid TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_GetProgress", ReplyAction="http://tempuri.org/IARS/Kern_GetProgressResponse")]
        System.Threading.Tasks.Task<string> Kern_GetProgressAsync(System.Guid AuthToken, System.Guid TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_GetTransactionMessages", ReplyAction="http://tempuri.org/IARS/Kern_GetTransactionMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="Invalid Token Exception", Name="Kern_GTM00")]
        RefundHandlingWeb.ARSReference.ComponentMessage[] Kern_GetTransactionMessages(System.Guid AuthToken, System.Guid TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/Kern_GetTransactionMessages", ReplyAction="http://tempuri.org/IARS/Kern_GetTransactionMessagesResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.ComponentMessage[]> Kern_GetTransactionMessagesAsync(System.Guid AuthToken, System.Guid TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/ANC_RetrieveSVCQueue", ReplyAction="http://tempuri.org/IARS/ANC_RetrieveSVCQueueResponse")]
        string ANC_RetrieveSVCQueue(System.Guid AuthToken, int QueueNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/ANC_RetrieveSVCQueue", ReplyAction="http://tempuri.org/IARS/ANC_RetrieveSVCQueueResponse")]
        System.Threading.Tasks.Task<string> ANC_RetrieveSVCQueueAsync(System.Guid AuthToken, int QueueNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/ASW_CheckAgencyUmsaetze", ReplyAction="http://tempuri.org/IARS/ASW_CheckAgencyUmsaetzeResponse")]
        string ASW_CheckAgencyUmsaetze(System.Guid AuthToken, string iata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/ASW_CheckAgencyUmsaetze", ReplyAction="http://tempuri.org/IARS/ASW_CheckAgencyUmsaetzeResponse")]
        System.Threading.Tasks.Task<string> ASW_CheckAgencyUmsaetzeAsync(System.Guid AuthToken, string iata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_CompleteCheckFQ", ReplyAction="http://tempuri.org/IARS/CAT15_CompleteCheckFQResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.DelayedAnswerException), Action="http://tempuri.org/IARS/CAT15_CompleteCheckFQDelayedAnswerExceptionFault", Name="DelayedAnswerException", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
        RefundHandlingWeb.ARSReference.FareDisplay CAT15_CompleteCheckFQ(System.Guid AuthToken, string Airline, string Origin, string Destination, string Datum, string RequestType, string BookingCode, string CabinClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_CompleteCheckFQ", ReplyAction="http://tempuri.org/IARS/CAT15_CompleteCheckFQResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_CompleteCheckFQAsync(System.Guid AuthToken, string Airline, string Origin, string Destination, string Datum, string RequestType, string BookingCode, string CabinClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_ListFQ", ReplyAction="http://tempuri.org/IARS/CAT15_ListFQResponse")]
        RefundHandlingWeb.ARSReference.FareDisplay CAT15_ListFQ(System.Guid AuthToken, string Airline, string Origin, string Destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_ListFQ", ReplyAction="http://tempuri.org/IARS/CAT15_ListFQResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_ListFQAsync(System.Guid AuthToken, string Airline, string Origin, string Destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_CheckLineFQ", ReplyAction="http://tempuri.org/IARS/CAT15_CheckLineFQResponse")]
        RefundHandlingWeb.ARSReference.FareDisplay CAT15_CheckLineFQ(System.Guid AuthToken, string Airline, string Origin, string Destination, string Line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_CheckLineFQ", ReplyAction="http://tempuri.org/IARS/CAT15_CheckLineFQResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_CheckLineFQAsync(System.Guid AuthToken, string Airline, string Origin, string Destination, string Line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_PreviousCheckFQ", ReplyAction="http://tempuri.org/IARS/CAT15_PreviousCheckFQResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.DelayedAnswerException), Action="http://tempuri.org/IARS/CAT15_PreviousCheckFQDelayedAnswerExceptionFault", Name="DelayedAnswerException", Namespace="http://schemas.datacontract.org/2004/07/ARSWcf")]
        RefundHandlingWeb.ARSReference.FareDisplay CAT15_PreviousCheckFQ(System.Guid AuthToken, System.Guid FareId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/CAT15_PreviousCheckFQ", ReplyAction="http://tempuri.org/IARS/CAT15_PreviousCheckFQResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_PreviousCheckFQAsync(System.Guid AuthToken, System.Guid FareId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/HRG_GetUSDEURConversion", ReplyAction="http://tempuri.org/IARS/HRG_GetUSDEURConversionResponse")]
        bool HRG_GetUSDEURConversion(System.Guid AuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/HRG_GetUSDEURConversion", ReplyAction="http://tempuri.org/IARS/HRG_GetUSDEURConversionResponse")]
        System.Threading.Tasks.Task<bool> HRG_GetUSDEURConversionAsync(System.Guid AuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/HRS_RetrieveEmailFromPNR", ReplyAction="http://tempuri.org/IARS/HRS_RetrieveEmailFromPNRResponse")]
        RefundHandlingWeb.ARSReference.HRS_RetrieveEmailFromPNRResponse HRS_RetrieveEmailFromPNR(System.Guid AuthToken, string PNR, string IATA, string PNRName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/HRS_RetrieveEmailFromPNR", ReplyAction="http://tempuri.org/IARS/HRS_RetrieveEmailFromPNRResponse")]
        System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.HRS_RetrieveEmailFromPNRResponse> HRS_RetrieveEmailFromPNRAsync(System.Guid AuthToken, string PNR, string IATA, string PNRName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_AddRefund", ReplyAction="http://tempuri.org/IARS/RAC_AddRefundResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RefundHandlingWeb.ARSReference.ARSException), Action="An error ocurred while calling RAC_AddRefund", Name="RAC_ADD00")]
        void RAC_AddRefund(System.Guid AuthToken, RefundHandlingWeb.ARSReference.RefundAppInfo RefundApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_AddRefund", ReplyAction="http://tempuri.org/IARS/RAC_AddRefundResponse")]
        System.Threading.Tasks.Task RAC_AddRefundAsync(System.Guid AuthToken, RefundHandlingWeb.ARSReference.RefundAppInfo RefundApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_GetRefundURL", ReplyAction="http://tempuri.org/IARS/RAC_GetRefundURLResponse")]
        string RAC_GetRefundURL(System.Guid AuthToken, string RA, string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_GetRefundURL", ReplyAction="http://tempuri.org/IARS/RAC_GetRefundURLResponse")]
        System.Threading.Tasks.Task<string> RAC_GetRefundURLAsync(System.Guid AuthToken, string RA, string countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_ProcessRefundList", ReplyAction="http://tempuri.org/IARS/RAC_ProcessRefundListResponse")]
        bool RAC_ProcessRefundList(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_ProcessRefundList", ReplyAction="http://tempuri.org/IARS/RAC_ProcessRefundListResponse")]
        System.Threading.Tasks.Task<bool> RAC_ProcessRefundListAsync(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_RARealTimeCheck", ReplyAction="http://tempuri.org/IARS/RAC_RARealTimeCheckResponse")]
        bool RAC_RARealTimeCheck(System.Guid AuthToken, System.Guid RAId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_RARealTimeCheck", ReplyAction="http://tempuri.org/IARS/RAC_RARealTimeCheckResponse")]
        System.Threading.Tasks.Task<bool> RAC_RARealTimeCheckAsync(System.Guid AuthToken, System.Guid RAId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_UpdateNUCs", ReplyAction="http://tempuri.org/IARS/RAC_UpdateNUCsResponse")]
        bool RAC_UpdateNUCs(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/RAC_UpdateNUCs", ReplyAction="http://tempuri.org/IARS/RAC_UpdateNUCsResponse")]
        System.Threading.Tasks.Task<bool> RAC_UpdateNUCsAsync(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateBSPTable", ReplyAction="http://tempuri.org/IARS/UpdateBSPTableResponse")]
        bool UpdateBSPTable(System.Guid AuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateBSPTable", ReplyAction="http://tempuri.org/IARS/UpdateBSPTableResponse")]
        System.Threading.Tasks.Task<bool> UpdateBSPTableAsync(System.Guid AuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateDACTable", ReplyAction="http://tempuri.org/IARS/UpdateDACTableResponse")]
        bool UpdateDACTable(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateDACTable", ReplyAction="http://tempuri.org/IARS/UpdateDACTableResponse")]
        System.Threading.Tasks.Task<bool> UpdateDACTableAsync(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateGSATable", ReplyAction="http://tempuri.org/IARS/UpdateGSATableResponse")]
        bool UpdateGSATable(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateGSATable", ReplyAction="http://tempuri.org/IARS/UpdateGSATableResponse")]
        System.Threading.Tasks.Task<bool> UpdateGSATableAsync(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateGSATableForCountry", ReplyAction="http://tempuri.org/IARS/UpdateGSATableForCountryResponse")]
        string[] UpdateGSATableForCountry(System.Guid Token, string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateGSATableForCountry", ReplyAction="http://tempuri.org/IARS/UpdateGSATableForCountryResponse")]
        System.Threading.Tasks.Task<string[]> UpdateGSATableForCountryAsync(System.Guid Token, string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateIETTable", ReplyAction="http://tempuri.org/IARS/UpdateIETTableResponse")]
        bool UpdateIETTable(System.Guid Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IARS/UpdateIETTable", ReplyAction="http://tempuri.org/IARS/UpdateIETTableResponse")]
        System.Threading.Tasks.Task<bool> UpdateIETTableAsync(System.Guid Token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IARSChannel : RefundHandlingWeb.ARSReference.IARS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ARSClient : System.ServiceModel.ClientBase<RefundHandlingWeb.ARSReference.IARS>, RefundHandlingWeb.ARSReference.IARS {
        
        public ARSClient() {
        }
        
        public ARSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ARSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ARSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ARSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Kern_SendSingleCommand(System.Guid AuthToken, string Command) {
            return base.Channel.Kern_SendSingleCommand(AuthToken, Command);
        }
        
        public System.Threading.Tasks.Task<string> Kern_SendSingleCommandAsync(System.Guid AuthToken, string Command) {
            return base.Channel.Kern_SendSingleCommandAsync(AuthToken, Command);
        }
        
        public RefundHandlingWeb.ARSReference.Transaction Kern_StartMultipleCommand(System.Guid AuthToken, string Command) {
            return base.Channel.Kern_StartMultipleCommand(AuthToken, Command);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.Transaction> Kern_StartMultipleCommandAsync(System.Guid AuthToken, string Command) {
            return base.Channel.Kern_StartMultipleCommandAsync(AuthToken, Command);
        }
        
        public string Kern_SendMultipleCommand(System.Guid AuthToken, System.Guid TransactionId, string Command) {
            return base.Channel.Kern_SendMultipleCommand(AuthToken, TransactionId, Command);
        }
        
        public System.Threading.Tasks.Task<string> Kern_SendMultipleCommandAsync(System.Guid AuthToken, System.Guid TransactionId, string Command) {
            return base.Channel.Kern_SendMultipleCommandAsync(AuthToken, TransactionId, Command);
        }
        
        public string Kern_SendMultipleCommandNoWait(System.Guid AuthToken, System.Guid TransactionId, string Command) {
            return base.Channel.Kern_SendMultipleCommandNoWait(AuthToken, TransactionId, Command);
        }
        
        public System.Threading.Tasks.Task<string> Kern_SendMultipleCommandNoWaitAsync(System.Guid AuthToken, System.Guid TransactionId, string Command) {
            return base.Channel.Kern_SendMultipleCommandNoWaitAsync(AuthToken, TransactionId, Command);
        }
        
        public void Kern_EndMultipleCommand(System.Guid AuthToken, System.Guid TransactionId) {
            base.Channel.Kern_EndMultipleCommand(AuthToken, TransactionId);
        }
        
        public System.Threading.Tasks.Task Kern_EndMultipleCommandAsync(System.Guid AuthToken, System.Guid TransactionId) {
            return base.Channel.Kern_EndMultipleCommandAsync(AuthToken, TransactionId);
        }
        
        public string Kern_GetProgress(System.Guid AuthToken, System.Guid TransactionId) {
            return base.Channel.Kern_GetProgress(AuthToken, TransactionId);
        }
        
        public System.Threading.Tasks.Task<string> Kern_GetProgressAsync(System.Guid AuthToken, System.Guid TransactionId) {
            return base.Channel.Kern_GetProgressAsync(AuthToken, TransactionId);
        }
        
        public RefundHandlingWeb.ARSReference.ComponentMessage[] Kern_GetTransactionMessages(System.Guid AuthToken, System.Guid TransactionId) {
            return base.Channel.Kern_GetTransactionMessages(AuthToken, TransactionId);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.ComponentMessage[]> Kern_GetTransactionMessagesAsync(System.Guid AuthToken, System.Guid TransactionId) {
            return base.Channel.Kern_GetTransactionMessagesAsync(AuthToken, TransactionId);
        }
        
        public string ANC_RetrieveSVCQueue(System.Guid AuthToken, int QueueNumber) {
            return base.Channel.ANC_RetrieveSVCQueue(AuthToken, QueueNumber);
        }
        
        public System.Threading.Tasks.Task<string> ANC_RetrieveSVCQueueAsync(System.Guid AuthToken, int QueueNumber) {
            return base.Channel.ANC_RetrieveSVCQueueAsync(AuthToken, QueueNumber);
        }
        
        public string ASW_CheckAgencyUmsaetze(System.Guid AuthToken, string iata) {
            return base.Channel.ASW_CheckAgencyUmsaetze(AuthToken, iata);
        }
        
        public System.Threading.Tasks.Task<string> ASW_CheckAgencyUmsaetzeAsync(System.Guid AuthToken, string iata) {
            return base.Channel.ASW_CheckAgencyUmsaetzeAsync(AuthToken, iata);
        }
        
        public RefundHandlingWeb.ARSReference.FareDisplay CAT15_CompleteCheckFQ(System.Guid AuthToken, string Airline, string Origin, string Destination, string Datum, string RequestType, string BookingCode, string CabinClass) {
            return base.Channel.CAT15_CompleteCheckFQ(AuthToken, Airline, Origin, Destination, Datum, RequestType, BookingCode, CabinClass);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_CompleteCheckFQAsync(System.Guid AuthToken, string Airline, string Origin, string Destination, string Datum, string RequestType, string BookingCode, string CabinClass) {
            return base.Channel.CAT15_CompleteCheckFQAsync(AuthToken, Airline, Origin, Destination, Datum, RequestType, BookingCode, CabinClass);
        }
        
        public RefundHandlingWeb.ARSReference.FareDisplay CAT15_ListFQ(System.Guid AuthToken, string Airline, string Origin, string Destination) {
            return base.Channel.CAT15_ListFQ(AuthToken, Airline, Origin, Destination);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_ListFQAsync(System.Guid AuthToken, string Airline, string Origin, string Destination) {
            return base.Channel.CAT15_ListFQAsync(AuthToken, Airline, Origin, Destination);
        }
        
        public RefundHandlingWeb.ARSReference.FareDisplay CAT15_CheckLineFQ(System.Guid AuthToken, string Airline, string Origin, string Destination, string Line) {
            return base.Channel.CAT15_CheckLineFQ(AuthToken, Airline, Origin, Destination, Line);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_CheckLineFQAsync(System.Guid AuthToken, string Airline, string Origin, string Destination, string Line) {
            return base.Channel.CAT15_CheckLineFQAsync(AuthToken, Airline, Origin, Destination, Line);
        }
        
        public RefundHandlingWeb.ARSReference.FareDisplay CAT15_PreviousCheckFQ(System.Guid AuthToken, System.Guid FareId) {
            return base.Channel.CAT15_PreviousCheckFQ(AuthToken, FareId);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.FareDisplay> CAT15_PreviousCheckFQAsync(System.Guid AuthToken, System.Guid FareId) {
            return base.Channel.CAT15_PreviousCheckFQAsync(AuthToken, FareId);
        }
        
        public bool HRG_GetUSDEURConversion(System.Guid AuthToken) {
            return base.Channel.HRG_GetUSDEURConversion(AuthToken);
        }
        
        public System.Threading.Tasks.Task<bool> HRG_GetUSDEURConversionAsync(System.Guid AuthToken) {
            return base.Channel.HRG_GetUSDEURConversionAsync(AuthToken);
        }
        
        public RefundHandlingWeb.ARSReference.HRS_RetrieveEmailFromPNRResponse HRS_RetrieveEmailFromPNR(System.Guid AuthToken, string PNR, string IATA, string PNRName) {
            return base.Channel.HRS_RetrieveEmailFromPNR(AuthToken, PNR, IATA, PNRName);
        }
        
        public System.Threading.Tasks.Task<RefundHandlingWeb.ARSReference.HRS_RetrieveEmailFromPNRResponse> HRS_RetrieveEmailFromPNRAsync(System.Guid AuthToken, string PNR, string IATA, string PNRName) {
            return base.Channel.HRS_RetrieveEmailFromPNRAsync(AuthToken, PNR, IATA, PNRName);
        }
        
        public void RAC_AddRefund(System.Guid AuthToken, RefundHandlingWeb.ARSReference.RefundAppInfo RefundApplication) {
            base.Channel.RAC_AddRefund(AuthToken, RefundApplication);
        }
        
        public System.Threading.Tasks.Task RAC_AddRefundAsync(System.Guid AuthToken, RefundHandlingWeb.ARSReference.RefundAppInfo RefundApplication) {
            return base.Channel.RAC_AddRefundAsync(AuthToken, RefundApplication);
        }
        
        public string RAC_GetRefundURL(System.Guid AuthToken, string RA, string countryCode) {
            return base.Channel.RAC_GetRefundURL(AuthToken, RA, countryCode);
        }
        
        public System.Threading.Tasks.Task<string> RAC_GetRefundURLAsync(System.Guid AuthToken, string RA, string countryCode) {
            return base.Channel.RAC_GetRefundURLAsync(AuthToken, RA, countryCode);
        }
        
        public bool RAC_ProcessRefundList(System.Guid Token) {
            return base.Channel.RAC_ProcessRefundList(Token);
        }
        
        public System.Threading.Tasks.Task<bool> RAC_ProcessRefundListAsync(System.Guid Token) {
            return base.Channel.RAC_ProcessRefundListAsync(Token);
        }
        
        public bool RAC_RARealTimeCheck(System.Guid AuthToken, System.Guid RAId) {
            return base.Channel.RAC_RARealTimeCheck(AuthToken, RAId);
        }
        
        public System.Threading.Tasks.Task<bool> RAC_RARealTimeCheckAsync(System.Guid AuthToken, System.Guid RAId) {
            return base.Channel.RAC_RARealTimeCheckAsync(AuthToken, RAId);
        }
        
        public bool RAC_UpdateNUCs(System.Guid Token) {
            return base.Channel.RAC_UpdateNUCs(Token);
        }
        
        public System.Threading.Tasks.Task<bool> RAC_UpdateNUCsAsync(System.Guid Token) {
            return base.Channel.RAC_UpdateNUCsAsync(Token);
        }
        
        public bool UpdateBSPTable(System.Guid AuthToken) {
            return base.Channel.UpdateBSPTable(AuthToken);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBSPTableAsync(System.Guid AuthToken) {
            return base.Channel.UpdateBSPTableAsync(AuthToken);
        }
        
        public bool UpdateDACTable(System.Guid Token) {
            return base.Channel.UpdateDACTable(Token);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDACTableAsync(System.Guid Token) {
            return base.Channel.UpdateDACTableAsync(Token);
        }
        
        public bool UpdateGSATable(System.Guid Token) {
            return base.Channel.UpdateGSATable(Token);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateGSATableAsync(System.Guid Token) {
            return base.Channel.UpdateGSATableAsync(Token);
        }
        
        public string[] UpdateGSATableForCountry(System.Guid Token, string Country) {
            return base.Channel.UpdateGSATableForCountry(Token, Country);
        }
        
        public System.Threading.Tasks.Task<string[]> UpdateGSATableForCountryAsync(System.Guid Token, string Country) {
            return base.Channel.UpdateGSATableForCountryAsync(Token, Country);
        }
        
        public bool UpdateIETTable(System.Guid Token) {
            return base.Channel.UpdateIETTable(Token);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateIETTableAsync(System.Guid Token) {
            return base.Channel.UpdateIETTableAsync(Token);
        }
    }
}
